"""empty message

Revision ID: 281c6a95cccb
Revises: 594dcefb1c3e
Create Date: 2019-04-22 19:03:07.674973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281c6a95cccb'
down_revision = '594dcefb1c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due')
    # ### end Alembic commands ###
