"""empty message

Revision ID: 594dcefb1c3e
Revises: 03c927b317b3
Create Date: 2019-04-20 07:34:29.707425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594dcefb1c3e'
down_revision = '03c927b317b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
