"""empty message

Revision ID: b3981b942c80
Revises: 281c6a95cccb
Create Date: 2019-04-22 19:21:16.714640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3981b942c80'
down_revision = '281c6a95cccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
